name: push to server
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: webhook
        run: curl -I -u BuildUser:11da16b017ac2524573c9574afd83e1111 https://jenkins.startupmission.in/job/iedcsummit/build?token=iedcsummit
